// This file is generated by ./config.sh --objdir /usr/local/bin/oscam-svn/hi --make-config.mak
const char *config_mak =
  "\nCFG: strings FILE | sed -n 's/^CFG~//p' | openssl enc -d -base64 | gzip -d\n"
  "CFG~H4sIALWhJFYCA32UwXLcIAyG732KzOQFkmY2kxxykIWM1cVAAXt3c+ENeu/bF282\n"
  "CFG~MbZITx6+X5J/YVn3d+hszzqfOA05JvD89ufHvaQHgdE50wyfXl8eBIX3zp0FHREE\n"
  "CFG~M9xhuPjkivLJqeP+7e/mWOJmMk7v8a/fE4XLSpObcCjHnclo1vIDzJTV3C3dfOUF\n"
  "CFG~ApWjShkHCJFSXCUOipLLeqIY2VYOMGawiREiVraW9ynqpipwdGoyVB6Wkwu7WNNt\n"
  "CFG~KiLgQHSu2CnjBUt64XisWzOo4uS9C6m+VUMV/axhHB57PtfZ7OfnRvrNK8Konp7W\n"
  "CFG~CjU+iM4+cE7ohWTptKgyBQtu0Vg+AAlBL/O0hwEUaYhJCLFVO1JgMPKVzsaEJ8E9\n"
  "CFG~WOUCSCdDSn73DRGCWiaIwnaiKGQLui5yox8zJXA5wVnS6/9xcuEYhRYJZfWZAbFM\n"
  "CFG~a0NQ5PRU3ApJ1Zd+Y8lZ3UM98jehm8zVlBB04L5nK6vrXfx6Y9kPjux2NiuVbaJg\n"
  "CFG~wciV0gpat9R/giJy00jEF7aPTWn09dTXOSME7ZqS6n6iG79pS+zevXZo9hBT2UDX\n"
  "CFG~KWsmFjPpm6Iey5b6Klm2bh7ZsnmvvC8QKG5BwOctKP/n45aofU6ZMtiSjrWdlrv4\n"
  "CFG~B1/Ap0+CBgAA\n"
  ;
